# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GroovyCheck < Formula
  desc "Lint Groovy/Jenkinsfile code locally and validate declarative pipeline syntax against a live Jenkins server"
  homepage "https://github.com/aviadshiber/groovy-check"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aviadshiber/groovy-check/releases/download/v0.1.1/groovy-check_0.1.1_darwin_amd64.tar.gz"
      sha256 "87eaa682f1debceac6cde454aea2e0b15171e093f89df73cacbb11af4d527364"

      define_method(:install) do
        bin.install "groovy-check"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aviadshiber/groovy-check/releases/download/v0.1.1/groovy-check_0.1.1_darwin_arm64.tar.gz"
      sha256 "e00d87318be4180639010bc30b509bcaa9946767a3e2f201a628f01336c01e7a"

      define_method(:install) do
        bin.install "groovy-check"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviadshiber/groovy-check/releases/download/v0.1.1/groovy-check_0.1.1_linux_amd64.tar.gz"
      sha256 "79874489346afbfca04b9dc2d00f7a549b02f7af9c770ea715737352747ecd5e"
      define_method(:install) do
        bin.install "groovy-check"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviadshiber/groovy-check/releases/download/v0.1.1/groovy-check_0.1.1_linux_arm64.tar.gz"
      sha256 "64ef5de775487825decf31a7ef7c46de9b7f0320cc41d2fbd9aacdf8dc51c37e"
      define_method(:install) do
        bin.install "groovy-check"
      end
    end
  end

  test do
    system "#{bin}/groovy-check", "version"
  end
end
