class LangfuseCli < Formula
  include Language::Python::Virtualenv

  desc "Observability-first CLI for the Langfuse LLM platform"
  homepage "https://github.com/aviadshiber/langfuse-cli"
  url "https://files.pythonhosted.org/packages/source/l/langfuse-cli/langfuse_cli-0.1.0.tar.gz"
  sha256 "PLACEHOLDER_WILL_BE_UPDATED_ON_FIRST_PYPI_RELEASE"
  license "MIT"

  depends_on "python@3.12"

  # Resource blocks will be auto-generated by homebrew-pypi-poet
  # after the first PyPI release via the update-homebrew GitHub Action.

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "lf", shell_output("#{bin}/lf --version")
  end
end
