# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lightctl < Formula
  desc "LightRun CLI -- runtime debugging tool"
  homepage ""
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aviadshiber/lightctl/releases/download/v0.1.0/lightctl_darwin_amd64.tar.gz"
      sha256 "ec3dbd6cc55f4a19f7f5bfd326846e5cc78ee4d46c284efc0db48efa0dcd3c4d"

      define_method(:install) do
        bin.install "lightctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aviadshiber/lightctl/releases/download/v0.1.0/lightctl_darwin_arm64.tar.gz"
      sha256 "ef9675f4d37cd47e6d3eb69fc7516341eb552b546b8ee3a3d876a57f5a434e1b"

      define_method(:install) do
        bin.install "lightctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviadshiber/lightctl/releases/download/v0.1.0/lightctl_linux_amd64.tar.gz"
      sha256 "9a81af512f8599cb84bc7297f7d1a4587d8d536026666e829b5229f3cb3969b3"
      define_method(:install) do
        bin.install "lightctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviadshiber/lightctl/releases/download/v0.1.0/lightctl_linux_arm64.tar.gz"
      sha256 "28ab625ec8388000084adec45f8fd09b2254b082a4295a89b6f179f22b8e2f31"
      define_method(:install) do
        bin.install "lightctl"
      end
    end
  end
end
