# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mp < Formula
  desc "Mixpanel CLI - query analytics from your terminal"
  homepage "https://github.com/aviadshiber/mp"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aviadshiber/mp/releases/download/v0.1.2/mp_0.1.2_darwin_amd64.tar.gz"
      sha256 "d0ef31d5241d2a4fb927fa8600fbf6c444e7e847d541aef11bef45cef24c8b34"

      define_method(:install) do
        bin.install "mp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aviadshiber/mp/releases/download/v0.1.2/mp_0.1.2_darwin_arm64.tar.gz"
      sha256 "41ef14c60a3781e648562db1486d03a563590c629166985083d679290f6094d9"

      define_method(:install) do
        bin.install "mp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviadshiber/mp/releases/download/v0.1.2/mp_0.1.2_linux_amd64.tar.gz"
      sha256 "895b75c21c30e8fb3891ac039768b42f342d2bd85875d510524a21b1cb0f9ad9"
      define_method(:install) do
        bin.install "mp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviadshiber/mp/releases/download/v0.1.2/mp_0.1.2_linux_arm64.tar.gz"
      sha256 "8032703a14188d358c15a07076008f00a14fc31a72a857fe4f3b19fd94333b4d"
      define_method(:install) do
        bin.install "mp"
      end
    end
  end

  test do
    system "#{bin}/mp", "version"
  end
end
