# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mp < Formula
  desc "Mixpanel CLI - query analytics from your terminal"
  homepage "https://github.com/aviadshiber/mp"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aviadshiber/mp/releases/download/v0.1.0/mp_0.1.0_darwin_amd64.tar.gz"
      sha256 "f758082b9553843e70120ed91cc2bdc7bd62aeeac55c883efbdd2069ba6bc15c"

      define_method(:install) do
        bin.install "mp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aviadshiber/mp/releases/download/v0.1.0/mp_0.1.0_darwin_arm64.tar.gz"
      sha256 "e46317fd77438fff51352e6b2e530b842b14cc5deca608d12ec738caf4623817"

      define_method(:install) do
        bin.install "mp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviadshiber/mp/releases/download/v0.1.0/mp_0.1.0_linux_amd64.tar.gz"
      sha256 "12472151546c94640f82e145ba1cc395500d3d18f4e8c2f13358a5648c81b291"
      define_method(:install) do
        bin.install "mp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviadshiber/mp/releases/download/v0.1.0/mp_0.1.0_linux_arm64.tar.gz"
      sha256 "6bb04d360626dc24b445b94ad5a72f27142a6ba9134ae8e185dc1f2bdfa634dd"
      define_method(:install) do
        bin.install "mp"
      end
    end
  end

  test do
    system "#{bin}/mp", "version"
  end
end
