# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mp < Formula
  desc "Mixpanel CLI - query analytics from your terminal"
  homepage "https://github.com/aviadshiber/mp"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aviadshiber/mp/releases/download/v0.1.1/mp_0.1.1_darwin_amd64.tar.gz"
      sha256 "845e4cc7d203ecba74c668abc631fb261fca174c3c40c3f0eaeff91b5931fb3e"

      define_method(:install) do
        bin.install "mp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aviadshiber/mp/releases/download/v0.1.1/mp_0.1.1_darwin_arm64.tar.gz"
      sha256 "6658ddfe9f99a321bf5a0278ff2d14ef6ec8ba00dd375da5605544fa6324bc0c"

      define_method(:install) do
        bin.install "mp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviadshiber/mp/releases/download/v0.1.1/mp_0.1.1_linux_amd64.tar.gz"
      sha256 "c4c4b0edac59d50b65ac61cdf075596276d950c5f0ca07ea243f45b53aea88ef"
      define_method(:install) do
        bin.install "mp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviadshiber/mp/releases/download/v0.1.1/mp_0.1.1_linux_arm64.tar.gz"
      sha256 "ab52d59caf097dfb0aea2e9ab66733982110901fad368ef2ab36bca83e7fe462"
      define_method(:install) do
        bin.install "mp"
      end
    end
  end

  test do
    system "#{bin}/mp", "version"
  end
end
